date.timezone=America/Argentina/Buenos_Aires
session.auto_start=Off
short_open_tag=Off
memory_limit=3G
max_execution_time=300
upload_max_filesize=1G
post_max_size=2G
error_log=/var/log/php-fpm.log
log_errors=On
apc.enable_cli=1